from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors

def generate_pdf(filename, data):
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(filename, pagesize=A4)
    elements = []

    # Header
    elements.append(Paragraph(
        "<b>Women’s Health Care Center</b>",
        styles["Title"]
    ))
    elements.append(Paragraph(
        "AI-Assisted Gynecological Screening Report",
        styles["Heading2"]
    ))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(
        f"<b>Report ID:</b> {data['report_id']}<br/>"
        f"<b>Date:</b> {data['date']}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 14))

    # Symptom summary
    elements.append(Paragraph("<b>1. Symptom Summary</b>", styles["Heading3"]))
    elements.append(Paragraph(
        "Patient-reported symptoms were analyzed to evaluate pain patterns, "
        "menstrual characteristics, digestive symptoms, and functional impact.",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 10))

    # Pain assessment
    elements.append(Paragraph(
        "<b>2. Pain Assessment (Clinical Interpretation)</b>",
        styles["Heading3"]
    ))

    pain_table = [
        ["Pain Scale (0–10)", "Clinical Meaning", "Description"],
        ["0 – 3", "Normal / Mild Pain",
         "Occasional discomfort with minimal impact on daily activities"],
        ["4 – 6", "Moderate Pain",
         "Persistent pain causing noticeable daily activity limitation"],
        ["7 – 10", "Severe Pain",
         "Continuous or intense pain significantly affecting quality of life"]
    ]

    table = Table(pain_table, colWidths=[90, 140, 260])
    table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 1, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.whitesmoke)
    ]))
    elements.append(table)
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(
        "<b>Assessment Result:</b> " +
        (
            "The symptom pattern corresponds to a moderate-to-severe (≥4/10) pain level, "
            "which is considered clinically abnormal."
            if data["risk_score"] >= 6
            else
            "The symptom pattern corresponds to a mild (≤3/10) pain level, "
            "within normal clinical limits."
        ),
        styles["Normal"]
    ))
    elements.append(Spacer(1, 12))

    # Imaging findings
    elements.append(Paragraph("<b>3. Imaging Findings</b>", styles["Heading3"]))
    if data.get("findings"):
        img_table = [["Imaging Modality", "Finding", "Model Confidence"]]
        for i, f in enumerate(data["findings"]):
            modality = "Ultrasound" if "Ultrasound" in f else "Endoscopy"
            img_table.append([modality, f, data["confidences"][i]])

        table = Table(img_table, colWidths=[100, 260, 140])
        table.setStyle(TableStyle([
            ("GRID", (0,0), (-1,-1), 1, colors.grey),
            ("BACKGROUND", (0,0), (-1,0), colors.whitesmoke)
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph(
            "No imaging data was provided for this assessment.",
            styles["Normal"]
        ))
    elements.append(Spacer(1, 12))

    # Risk assessment
    elements.append(Paragraph(
        "<b>4. Overall Clinical Risk Assessment</b>",
        styles["Heading3"]
    ))
    elements.append(Paragraph(
        f"<b>{data['risk_level']}</b><br/>"
        f"Overall Risk Score: {data['risk_score']}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 12))

    # Recommendations
    elements.append(Paragraph("<b>5. Clinical Recommendations</b>", styles["Heading3"]))
    elements.append(Paragraph(
        "- Consultation with a gynecologist is advised.<br/>"
        "- Share this report with your healthcare provider.<br/>"
        "- Further diagnostic evaluation may be recommended based on clinical judgment.",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 14))

    # Disclaimer
    elements.append(Paragraph(
        "<i>This report is generated by an AI-assisted screening system "
        "and does not constitute a medical diagnosis.</i>",
        styles["Italic"]
    ))

    doc.build(elements)
